#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Lint the first project
if ! cd ./client;
then
  echo "$1 failed with exit code $?"
  exit 1
fi
npm run lint:fix
echo "Client lint:fix successful"

# Lint the second project
if ! cd ../server;
then
  echo "$1 failed with exit code $?"
  exit 1
fi
npm run lint:fix
echo "Server lint:fix successful"

